spring.application.name=BookMarket
server.servlet.context-path=/BookMarket

# ?? ??? ?? ?? ??
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# ??? ?? (D????)
file.uploadDir=D:/upload/

server.tomcat.max-http-form-post-size=200MB
server.tomcat.max-swallow-size=-1

spring.messages.encoding=utf-8
spring.messages.basename=messages